from dataclasses import dataclass
from pathlib import Path

# Because of dataclass, we don't have to write init method and other dunder methods. It will be automatically generated by dataclass.
@dataclass(frozen=True)
class DataIngestionConfig:
    root_dir: Path
    source_URL: str
    local_data_file: Path
    unzip_dir: Path